//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workplaces
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int UserRoleId { get; set; }
    
        public virtual UserRoles UserRoles { get; set; }
        public virtual Users Users { get; set; }
    }
}
